### ISSUE TITLE
Review SOME/IP up-spec change

### ISSUE THREAD

**Issue by gregmedd** [eclipse-uprotocol/up-client-vsomeip-cpp#11]
See: https://github.com/eclipse-uprotocol/up-spec/pull/165

**Comment by pranavishere2** [comment]
Me and ruchir are reviewing this spec. Kindly assign this to us.

**Comment by ruchirchauhan** [comment]
I am working on this review

**Comment by gregmedd** [comment]
The upstream task has been resolved. Closing
