### ISSUE TITLE
Prepare up-client-vsomeip-cpp repo for updated API

### ISSUE THREAD

**Issue by gregmedd** [eclipse-uprotocol/up-client-vsomeip-cpp#3]
See https://github.com/eclipse-uprotocol/up-client-zenoh-cpp/pull/48 for an example of what needs to be done.

**Comment by agosh01** [comment]
I can take this one

**Comment by agosh01** [comment]
PR: https://github.com/eclipse-uprotocol/up-tck/pull/41
